"""initial: content_queue and generation_log tables

Revision ID: 3f2398b53f3d
Revises: 
Create Date: 2026-04-06 21:31:03.839992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f2398b53f3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('hot_take', 'data_drop', 'trend_jack', name='content_type_enum'), nullable=False),
    sa.Column('pillar', sa.Enum('blind_spot', 'cost_of_guessing', 'client_proof', 'thought_leadership', 'product', name='pillar_enum'), nullable=False),
    sa.Column('intent', sa.Enum('brand', 'partner', 'revenue', name='intent_enum'), nullable=False),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'publishing', 'published', 'publishing_unknown', 'failed', 'rejected', name='status_enum'), nullable=False),
    sa.Column('variant_group', sa.UUID(), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('tweet_id', sa.String(length=64), nullable=True),
    sa.Column('compliance_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regeneration_count', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_queue_id', sa.UUID(), nullable=True),
    sa.Column('prompt_snapshot', sa.Text(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_log')
    op.drop_table('content_queue')
    # ### end Alembic commands ###
